###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID cad29)
#  Generated on:      Tue Dec 21 15:49:15 2021
#  Design:            CHIP
#  Command:           create_ccopt_clock_tree_spec -file ./ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin CLK true

# Clocks present at pin CLK
#   CLK1 (period 10.000ns) in timing_config func_mode([design_data/CHIP_cts.sdc])
#   CLK1 (period 100.000ns) in timing_config scan_mode([design_data/CHIP_scan_cts.sdc])
create_ccopt_clock_tree -name CLK1 -source CLK -no_skew_group

# Clock period setting for source pin of CLK1
set_ccopt_property clock_period -pin CLK 10

# Skew group to balance non generated clock:CLK1 in timing_config:func_mode (sdc design_data/CHIP_cts.sdc)
create_ccopt_skew_group -name CLK1/func_mode -sources CLK -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK1/func_mode true
set_ccopt_property extracted_from_clock_name -skew_group CLK1/func_mode CLK1
set_ccopt_property extracted_from_constraint_mode_name -skew_group CLK1/func_mode func_mode
set_ccopt_property extracted_from_delay_corners -skew_group CLK1/func_mode {Delay_Corner_max Delay_Corner_min}

# Skew group to balance non generated clock:CLK1 in timing_config:scan_mode (sdc design_data/CHIP_scan_cts.sdc)
create_ccopt_skew_group -name CLK1/scan_mode -sources CLK -auto_sinks
set_ccopt_property include_source_latency -skew_group CLK1/scan_mode true
set_ccopt_property target_insertion_delay -skew_group CLK1/scan_mode 2.000
set_ccopt_property extracted_from_clock_name -skew_group CLK1/scan_mode CLK1
set_ccopt_property extracted_from_constraint_mode_name -skew_group CLK1/scan_mode scan_mode
set_ccopt_property extracted_from_delay_corners -skew_group CLK1/scan_mode {Delay_Corner_max Delay_Corner_min}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

